### ISSUE TITLE
JourneyToTheEastRocks not linked in The Ballad of The First King book

### ISSUE THREAD

**Issue by Phoenyx65535** [Lucas-C/undying-dusk#17]
Currently, the space where it has the music icon is simply not a link.  The square is cut out of the "turn the page" link, but it doesn't link to the music.

**Comment by Lucas-C** [comment]
Thank you very much for this bug report @Phoenyx65535! 👍

I fixed that in https://github.com/Lucas-C/undying-dusk/commit/c2d0fc59fa4c6e5f0ba528dc4f1613981586cfb5

**Comment by Phoenyx65535** [comment]
I'm sorry to say but I don't think it was fixed then :(   I compiled it about 4 days ago from the latest code, and it still doesn't seem to work.  I have multiple versions of Sumatra (the one packaged with it that I started with and an updated one I downloaded so it could highlight links when I was searching for secrets), and they apparently behave differently (but neither links to the music).  The one I downloaded with the pdf just turns the page, like the rest of the book around it, while the updated one does nothing for the square.  If there are 2 links in the same place, I wonder if Sumatra is not happy with that (in one case, guesses wrong which we want, and in the other case, just doesn't link anywhere because it doesn't know which one).

**Comment by Lucas-C** [comment]
> I'm sorry to say but I don't think it was fixed then :( I compiled it about 4 days ago from the latest code, and it still doesn't seem to work.

The commit I mentioned is from earlier today 😅

**Comment by Phoenyx65535** [comment]
Honestly, I bet it's just that I'm not used to people hearing feedback and just..... fixing it! 🤣

**Comment by Lucas-C** [comment]
No worries! 😊
