### ISSUE TITLE
Tutoriel : flèche de navigation inefficace

### ISSUE THREAD

**Issue by Anaguiros** [Lucas-C/undying-dusk#2]
Le clique sur la flèche de navigation de la 4ème page du tutoriel n'amène pas à la page suivante.

![undying-dusk_02](https://user-images.githubusercontent.com/548821/95436381-0f16fe00-0954-11eb-9b1d-8a5a587b1cba.jpg)

**Comment by Lucas-C** [comment]
Closed by 019c154
